#!/bin/bash
# 
# install bash dotfiles in $HOME

echo "installing dotfiles for $USER..."

# want backup
test -d $HOME/.local/bin/scripts && export PATH=$PATH:$HOME/.local/bin/scripts

function debug () {
	echo "bash_source: $BASH_SOURCE"
	echo "calling script (\$0): $0"
	echo "realpath $(realpath $BASH_SOURCE)"
	this_script=${BASH_SOURCE/*\//}
	this_script=${this_script/\//}
	echo "this script: $this_script"
}

this_script=${BASH_SOURCE/*\//}
this_script=${this_script/\//}

if [ "$0" == "$BASH_SOURCE" ]; then
	_bn="`pwd`/$(basename $0)"
	_rp="$(realpath $0)"
	[ "$_bn" != "$_rp" ] && echo "Must be run from same directory. Exiting!" &&  exit 1
	echo installing scripts
	this_dir=`pwd`
else
	# echo "this was sourced"
	this_dir=$(pwd)/dotfiles
fi

for script in `ls $this_dir`; do
	[ "$script" == "$this_script" ] && continue
	test -e $HOME/.$script && backup $HOME/.$script
	cp -v $this_dir/$script $HOME/.$script
done
