#!/bin/bash

VIM=`which vim`
GIT=`which git`
BKUP=`which backup`
test -z "$VIM" && echo Do you NAWT have vim installed?! Exiting!! && exit 1
test -z "$GIT" && echo Do you NAWT have git installed?! Exiting!! && exit 1
test -z "$BKUP" && echo Do you NAWT have backup set up in scripts dir?! Exiting!! && exit 1

if [ ! -d $HOME/.vim/autoload ]; then
  echo no autoload
  mkdir -p $HOME/.vim/.autoload
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

this_script=${BASH_SOURCE/*\//}
this_script=${this_script/\//}

if [ "$0" == "$BASH_SOURCE" ]; then
	_bn="`pwd`/$(basename $0)"
	_rp="$(realpath $0)"
	[ "$_bn" != "$_rp" ] && echo "Must be run from same directory. Exiting!" &&  exit 1
	echo installing scripts
	this_dir=`pwd`
else
	# echo "this was sourced"
	this_dir=$(pwd)/vim
fi

echo installing vim config...
backup ~/.vimrc
cp -v $this_dir/vimrc $HOME/.vimrc

#cp vimrc $HOME/.vimrc
# somehow run PlugInstall



