set nocompatible
set number
set ruler
" set mouse=a
set tabstop=2
set autoindent

" I think these are unique to vim, not vi
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
set smartindent
"syntax enable
colorscheme industry
"set textwidth=72

"set statusline+=&filetype

" Fancy maps





" disable arrow keys (vi muscle memory)
" because you're bold and daring
" noremap <up> :echoerr "Umm, use k instead"<CR>
" noremap <down> :echoerr "Umm, use j instead"<CR>
" noremap <left> :echoerr "Umm, use h instead"<CR>
" noremap <right> :echoerr "Umm, use l instead"<CR>
" inoremap <up> <NOP>
" inoremap <down> <NOP
" inoremap <left> <NOP>
" inoremap <right> <NOP>
"

" github.com/junegunn/vim-plug

if filereadable(expand('~/.vim/autoload/plug.vim'))

call plug#begin('~/.vim/plugged')
     Plug 'sheerun/vim-polyglot'
     Plug 'vim-pandoc/vim-pandoc'
     Plug 'rwxrob/vim-pandoc-syntax-simple'
     Plug 'pearofducks/ansible-vim'
call plug#end()

"else
 

  au BufRead,BufNewFile **/dyngrp_* set filetype=yaml.ansible
  let g:ansible_unindent_after_newline = 1

endif


