#!/bin/bash
# 
# install files in scripts direectory
this_dir=$(realpath "$0")
this_dir=$(dirname "$this_dir")

working_files_dir="$HOME"
repo_dotfiles_dir=$(dirname $(readlink -f "$0"))
mapfile -t tgt_files < <(find "$repo_dotfiles_dir" ! -name 'install*' ! -name '*.swp' -type f)

SCRIPTS=$HOME/.local/bin/scripts

function debug () {
	echo "bash_source: $BASH_SOURCE"
	echo "calling script (\$0): $0"
	echo "realpath $(realpath $BASH_SOURCE)"
	this_script=${BASH_SOURCE/*\//}
	this_script=${this_script/\//}
	echo "this script: $this_script"
}

function do_install(){
  echo installing scripts...
  test -d $SCRIPTS || mkdir -vp $SCRIPTS
  for df in "${tgt_files[@]}"; do
		#backup "$HOME/.${df##*/}"
		cp -v "$df" "$SCRIPTS/${df##*/}"
	done
}

do_install
