#!/bin/bash
# 
# install files in scripts direectory
SCRIPTS=$HOME/.local/bin/scripts


function compare () {
  for file in `ls $SCRIPTS`; do
    diff $file ./$file
  done
}

function debug () {
	echo "bash_source: $BASH_SOURCE"
	echo "calling script (\$0): $0"
	echo "realpath $(realpath $BASH_SOURCE)"
	this_script=${BASH_SOURCE/*\//}
	this_script=${this_script/\//}
	echo "this script: $this_script"
}

this_script=${BASH_SOURCE/*\//}
this_script=${this_script/\//}

if [ "$0" == "$BASH_SOURCE" ]; then
  # this script was invoked directly with ./
	_bn="`pwd`/$(basename $0)"
	_rp="$(realpath $0)"
	[ "$_bn" != "$_rp" ] && echo "Must be run from same directory. Exiting!" &&  exit 1
	echo installing scripts
	this_dir=`pwd`
else
	# echo "this was sourced"
	this_dir=$(pwd)/scripts
fi

function do_install(){
  echo installing scripts...
  test -d $SCRIPTS || mkdir -vp $SCRIPTS
  test -d $SCRIPTS/libs || mkdir -vp $SCRIPTS/libs
  for script in `ls $this_dir`; do
    [ "$script" == "$this_script" ] && continue
    cp -v $this_dir/$script $SCRIPTS
  done
}

do_install
