#!/bin/bash
notes_home="$HOME/.local/share/notes"
which drcat 2>&1 >/dev/null
[ "$?" -ne 0 ] && echo install drcat to use && exit 1

mkdir -p "$notes_home"

print_note() {
  drcat -f "$notes_home/$1.md"
}

case "$1" in 
  make|new|add) new_note "$1";;
  *) print_note "$@" ;;
esac
