#!/bin/bash
# Easily change link to current.html

[[ "$HOSTNAME" =~ homelab ]] # do everything via ssh instead

prjpath=/usr/share/nginx/twitch-project
declare -A prjs
pnames=(`ls -1 "$prjpath" | grep "project-" | sed -e 's/^.*-//; s/\..*//'`)

function add_prj() {
  echo TODO
}

function get_prj() {
  for i in project-define.html project-tagger.html; do 
    echo "$i" | sed -e 's/^.*-//; s/\..*//'
  done
}

function workon () {
  [ -z "$1" ] && printf "workon ... what, exactly?\n" && exit 1 
  ln -sTf "$prjpath/current.html" "$prjpath/$1.html"
}

